$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline

description: Finetuning pipeline for code generation

display_name: code-finetune-pipeline
experiment_name: code-finetune-pipeline
jobs:
  finetune:
    type: command
    inputs:
      checkpoint: "t5-small"
      #checkpoint: "Salesforce/codegen-350M-mono"
      data:
        type: uri_file
        path: azureml:functions:1
      batch_size: 20
      seq_length: 100
    code: ../src
    environment: azureml:pipeline_sweep_env@latest
    compute: azureml:cpu-inst
    command: >-
      python finetune.py --checkpoint ${{inputs.checkpoint}} --data_path ${{inputs.data}} --batch_size ${{inputs.batch_size}} --seq_lengh ${{inputs.seq_length}}

