$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline

description: Finetuning pipeline for code generation

display_name: code-finetune-pipeline
experiment_name: code-finetune-pipeline
jobs:
  finetune:
    type: command
    inputs:
      checkpoint: "stanford-crfm/alias-gpt2-small-x21"
      #checkpoint: "Salesforce/codegen-350M-mono"
      data:
        type: uri_file
        path: azureml:functions:1
      batch_size: 20
      seq_length: 100
    # outputs:
    #   model:
    #     type: mlflow_model
    code: ../src
    environment: azureml:codegen_env@latest
    compute: azureml:cpu-cheap
    command: >-
      python finetune.py --checkpoint ${{inputs.checkpoint}} --data_path ${{inputs.data}} --batch_size ${{inputs.batch_size}} --seq_length ${{inputs.seq_length}}


  predict:
    type: command
    inputs:
      checkpoint: "stanford-crfm/alias-gpt2-small-x21"
      data:
        type: uri_file
        path: azureml:test_functions:1
    code: ../src
    environment: azureml:codegen_env@latest
    compute: azureml:cpu-cheap
    command: >-
      python predict.py --checkpoint ${{inputs.checkpoint}} --test_data_path ${{inputs.test_data_path}}

