$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline

description: Finetuning pipeline for code generation

display_name: code-finetune-pipeline
experiment_name: code-finetune-pipeline
inputs:
  data:
    type: uri_file
    path: azureml:functions:1
  batch_size: 20
  seq_length: 100
  #checkpoint1: "stanford-crfm/alias-gpt2-small-x21"
  checkpoint1: "Salesforce/codegen-350M-mono"
  checkpoint2: "Deci/DeciCoder-1b"
outputs:
  model1:
    type: uri_folder
  model2:
    type: uri_folder
  results1:
    type: uri_folder
  results2:
    type: uri_folder
jobs:
  finetune_codegen:
    type: command
    inputs:
      checkpoint: ${{parent.inputs.checkpoint1}}
      #checkpoint: "Salesforce/codegen-350M-mono"
      data: ${{parent.inputs.data}}
      batch_size: ${{parent.inputs.batch_size}}
      seq_length: ${{parent.inputs.seq_length}}
    outputs:
      model:
        ${{parent.outputs.model1}}
        # name: "finetuned_codegen_model" # Define name and version to register a child job's output
        # version: "1"
    code: ../src
    environment: azureml:codegen_env@latest
    compute: azureml:cpu-cheap
    command: >-
      python finetune.py --checkpoint ${{inputs.checkpoint}} --data_path ${{inputs.data}} --batch_size ${{inputs.batch_size}} --seq_length ${{inputs.seq_length}} --model_dir ${{outputs.model}}

  predict_codegen:
    type: command
    inputs:
      checkpoint: ${{parent.inputs.checkpoint1}}
      model_folder: ${{parent.jobs.finetune_codegen.outputs.model}}
    outputs:
      output_dir:
        ${{parent.outputs.results1}}
        #type: uri_folder
    code: ../src
    environment: azureml:codegen_env@latest
    compute: azureml:cpu-cheap
    command: >-
      python predict.py --checkpoint ${{inputs.checkpoint}} --model_folder ${{inputs.model_folder}} --output_dir ${{outputs.output_dir}}

  finetune_deci:
    type: command
    inputs:
      checkpoint: ${{parent.inputs.checkpoint2}}
      data: ${{parent.inputs.data}}
      batch_size: ${{parent.inputs.batch_size}}
      seq_length: ${{parent.inputs.seq_length}}
    outputs:
      model:
        ${{parent.outputs.model2}}
        #name: "finetuned_decicoder_model" # Define name and version to register a child job's output
        #version: "1"
    code: ../src
    environment: azureml:codegen_env@latest
    compute: azureml:cpu-cheap
    command: >-
      python finetune.py --checkpoint ${{inputs.checkpoint}} --data_path ${{inputs.data}} --batch_size ${{inputs.batch_size}} --seq_length ${{inputs.seq_length}} --model_dir ${{outputs.model}}


  predict_deci:
    type: command
    inputs:
      checkpoint: ${{parent.inputs.checkpoint2}}
      model_folder: ${{parent.jobs.finetune_deci.outputs.model}}
    outputs:
      output_dir:
        ${{parent.outputs.results2}}
        #type: uri_folder
    code: ../src
    environment: azureml:codegen_env@latest
    compute: azureml:cpu-cheap
    command: >-
      python predict.py --checkpoint ${{inputs.checkpoint}} --model_folder ${{inputs.model_folder}} --output_dir ${{outputs.output_dir}}

