$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline

description: Finetuning pipeline for code generation

display_name: code-finetune-pipeline
experiment_name: code-finetune-pipeline
inputs:
  data:
    type: uri_file
    path: azureml:functions:1
  batch_size: 100
  seq_length: 500
  epochs: 6
  #checkpoint1: "stanford-crfm/alias-gpt2-small-x21"   # small model for testing
  checkpoint1: "Salesforce/codegen-350M-mono"
  checkpoint2: "Deci/DeciCoder-1b"
  checkpoint3: "codeparrot/codeparrot"
settings:
  default_compute: azureml:cpu-mid
outputs:
  model1:
    type: uri_folder
    name: finetuned_codegen_model
  model2:
    type: uri_folder
    name: finetuned_decicoder_model
  model3:
    type: uri_folder
    name: finetuned_codeparrot_model
  results1:
    type: uri_folder
  results2:
    type: uri_folder
  results3:
    type: uri_folder
jobs:
  finetune_codegen:
    type: command
    inputs:
      checkpoint: ${{parent.inputs.checkpoint1}}
      data: ${{parent.inputs.data}}
      batch_size: ${{parent.inputs.batch_size}}
      seq_length: ${{parent.inputs.seq_length}}
      epochs: ${{parent.inputs.epochs}}
    outputs:
      model: ${{parent.outputs.model1}}
    code: ../src
    environment: azureml:codegen_env:1
    command: >-
      python finetune.py --checkpoint ${{inputs.checkpoint}} --data_path ${{inputs.data}} --batch_size ${{inputs.batch_size}} --seq_length ${{inputs.seq_length}} --epochs ${{inputs.epochs}} --model_dir ${{outputs.model}}


  predict_codegen:
    type: command
    inputs:
      checkpoint: ${{parent.inputs.checkpoint1}}
      model_folder: ${{parent.jobs.finetune_codegen.outputs.model}}
    outputs:
      output_dir: ${{parent.outputs.results1}}
    code: ../src
    environment: azureml:codegen_env:1
    command: >-
      python predict.py --checkpoint ${{inputs.checkpoint}} --model_folder ${{inputs.model_folder}} --output_dir ${{outputs.output_dir}}


  finetune_deci:
    type: command
    inputs:
      checkpoint: ${{parent.inputs.checkpoint2}}
      data: ${{parent.inputs.data}}
      batch_size: ${{parent.inputs.batch_size}}
      seq_length: ${{parent.inputs.seq_length}}
      epochs: ${{parent.inputs.epochs}}
    outputs:
      model: ${{parent.outputs.model2}}
    code: ../src
    environment: azureml:codegen_env:1
    command: >-
      python finetune.py --checkpoint ${{inputs.checkpoint}} --data_path ${{inputs.data}} --batch_size ${{inputs.batch_size}} --seq_length ${{inputs.seq_length}} --epochs ${{inputs.epochs}} --model_dir ${{outputs.model}}


  predict_deci:
    type: command
    inputs:
      checkpoint: ${{parent.inputs.checkpoint2}}
      model_folder: ${{parent.jobs.finetune_deci.outputs.model}}
    outputs:
      output_dir: ${{parent.outputs.results2}}
    code: ../src
    environment: azureml:codegen_env:1
    command: >-
      python predict.py --checkpoint ${{inputs.checkpoint}} --model_folder ${{inputs.model_folder}} --output_dir ${{outputs.output_dir}}


  finetune_codeparrot:
    type: command
    inputs:
      checkpoint: ${{parent.inputs.checkpoint3}}
      data: ${{parent.inputs.data}}
      batch_size: ${{parent.inputs.batch_size}}
      seq_length: ${{parent.inputs.seq_length}}
      epochs: ${{parent.inputs.epochs}}
    outputs:
      model: ${{parent.outputs.model3}}
    code: ../src
    environment: azureml:codegen_env:1
    command: >-
      python finetune.py --checkpoint ${{inputs.checkpoint}} --data_path ${{inputs.data}} --batch_size ${{inputs.batch_size}} --seq_length ${{inputs.seq_length}} --epochs ${{inputs.epochs}} --model_dir ${{outputs.model}}


  predict_codeparrot:
    type: command
    inputs:
      checkpoint: ${{parent.inputs.checkpoint3}}
      model_folder: ${{parent.jobs.finetune_codeparrot.outputs.model}}
    outputs:
      output_dir: ${{parent.outputs.results3}}
    code: ../src
    environment: azureml:codegen_env:1
    command: >-
      python predict.py --checkpoint ${{inputs.checkpoint}} --model_folder ${{inputs.model_folder}} --output_dir ${{outputs.output_dir}}

