$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
type: command

name: train_model
display_name: train_model
version: 1

inputs:
  data_path:
    type: uri_file
  batch_size:
    type: integer
  learning_rate:
    type: number
  seq_length:
    type: integer
  epochs:
    type: integer

outputs:
  model_output:
    type: mlflow_model

code: ../src

environment: azureml:pipeline_sweep_env:1

command: >-
  python train.py
    --data_path ${{inputs.data_path}}
    --output_path ${{outputs.model_output}}
    --batch_size ${{inputs.batch_size}}
    --learning_rate ${{inputs.learning_rate}}
    --seq_length ${{inputs.seq_length}}
    --epochs ${{inputs.epochs}}

